-- =============================================================
-- FinGuard PostgreSQL Schema
-- Real-Time Financial Fraud Detection Pipeline
-- =============================================================

-- -------------------------------------------------------------
-- TABLE 1: transactions
-- The raw ledger. Every transaction ingested from Kafka lands here.
-- Source: consumers/consumer.py via KafkaConsumer
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS transactions (
    transaction_id      VARCHAR(50)     PRIMARY KEY,
    ts                  TIMESTAMP       NOT NULL,
    sender_account      VARCHAR(20)     NOT NULL,
    receiver_account    VARCHAR(20)     NOT NULL,
    amount              NUMERIC(15, 2)  NOT NULL,
    currency            VARCHAR(10)     DEFAULT 'EGP',
    sender_bank         VARCHAR(50),
    receiver_bank       VARCHAR(50),
    sender_country      VARCHAR(50)     DEFAULT 'Egypt',
    receiver_country    VARCHAR(50),
    transaction_type    VARCHAR(30),
    status              VARCHAR(20)     DEFAULT 'PROCESSED',
    ingested_at         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------
-- TABLE 2: fraud_alerts
-- Only flagged transactions. Written when alert != 'NORMAL'.
-- Source: consumers/consumer.py — second INSERT block
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fraud_alerts (
    alert_id            SERIAL          PRIMARY KEY,
    transaction_id      VARCHAR(50)     NOT NULL REFERENCES transactions(transaction_id),
    alert_type          VARCHAR(30)     NOT NULL,
    amount              NUMERIC(15, 2)  NOT NULL,
    sender_account      VARCHAR(20),
    receiver_account    VARCHAR(20),
    sender_bank         VARCHAR(50),
    receiver_country    VARCHAR(50),
    risk_level          VARCHAR(10)     GENERATED ALWAYS AS (
                            CASE
                                WHEN alert_type = 'MONEY LAUNDERING'  THEN 'CRITICAL'
                                WHEN alert_type = 'FRAUD DETECTED'    THEN 'HIGH'
                                WHEN alert_type = 'HIGH RISK COUNTRY' THEN 'HIGH'
                                WHEN alert_type = 'SUSPICIOUS'        THEN 'MEDIUM'
                                ELSE 'LOW'
                            END
                        ) STORED,
    detected_at         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------
-- TABLE 3: audit_log
-- Immutable record of every pipeline action for compliance.
-- Every INSERT, every Airflow task run, every schema change.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
    log_id              SERIAL          PRIMARY KEY,
    event_type          VARCHAR(50)     NOT NULL,
    component           VARCHAR(50),
    transaction_id      VARCHAR(50),
    description         TEXT,
    status              VARCHAR(20)     DEFAULT 'SUCCESS',
    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- Seed: log the schema creation itself
INSERT INTO audit_log (event_type, component, description)
VALUES ('SCHEMA_INIT', 'PostgreSQL', 'FinGuard schema initialised — 5 tables created')
ON CONFLICT DO NOTHING;

-- -------------------------------------------------------------
-- TABLE 4: high_risk_countries
-- Reference table for the fraud detection rule engine.
-- The Spark job and consumers check against this list.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS high_risk_countries (
    country_id          SERIAL          PRIMARY KEY,
    country_name        VARCHAR(100)    NOT NULL UNIQUE,
    country_code        CHAR(2),
    risk_category       VARCHAR(20)     NOT NULL,
    reason              TEXT,
    added_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    is_active           BOOLEAN         DEFAULT TRUE
);

-- Seed data — mirrors the isin() check in fraud_detector.py
INSERT INTO high_risk_countries (country_name, country_code, risk_category, reason) VALUES
    ('Russia',          'RU', 'CRITICAL', 'FATF grey list — high money laundering risk'),
    ('Nigeria',         'NG', 'CRITICAL', 'FATF grey list — high fraud and scam activity'),
    ('North Korea',     'KP', 'CRITICAL', 'FATF black list — state-sponsored financial crime'),
    ('Iran',            'IR', 'CRITICAL', 'FATF black list — sanctions violations'),
    ('Myanmar',         'MM', 'HIGH',     'FATF grey list — weak AML controls')
ON CONFLICT (country_name) DO NOTHING;

-- -------------------------------------------------------------
-- TABLE 5: daily_summary
-- Aggregated daily report generated by Airflow every midnight.
-- Powers dashboards and management reporting.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS daily_summary (
    summary_id          SERIAL          PRIMARY KEY,
    report_date         DATE            NOT NULL UNIQUE,
    total_transactions  INTEGER         DEFAULT 0,
    total_volume_egp    NUMERIC(20, 2)  DEFAULT 0,
    fraud_count         INTEGER         DEFAULT 0,
    laundering_count    INTEGER         DEFAULT 0,
    suspicious_count    INTEGER         DEFAULT 0,
    high_risk_count     INTEGER         DEFAULT 0,
    normal_count        INTEGER         DEFAULT 0,
    fraud_rate_pct      NUMERIC(5, 2)   GENERATED ALWAYS AS (
                            CASE
                                WHEN total_transactions = 0 THEN 0
                                ELSE ROUND((fraud_count * 100.0) / total_transactions, 2)
                            END
                        ) STORED,
    generated_at        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================
-- INDEXES — for query performance on large transaction volumes
-- =============================================================
CREATE INDEX IF NOT EXISTS idx_transactions_type
    ON transactions(transaction_type);

CREATE INDEX IF NOT EXISTS idx_transactions_ts
    ON transactions(ts);

CREATE INDEX IF NOT EXISTS idx_fraud_alerts_type
    ON fraud_alerts(alert_type);

CREATE INDEX IF NOT EXISTS idx_fraud_alerts_detected
    ON fraud_alerts(detected_at);

CREATE INDEX IF NOT EXISTS idx_audit_log_component
    ON audit_log(component, created_at);
